### ISSUE TITLE
Watchdog error: Cannot read LSP request: A Lean 3 request was received. Please ensure that your editor has a Lean 4 compatible extension installed. For VSCode, this is

### ISSUE THREAD

**Issue by enjoysmath** [leanprover-community/lean-client-python#24]
![image](https://github.com/leanprover-community/lean-client-python/assets/1606391/fc5a1f67-75b2-48e0-a5d1-b7c22e4ba109)

```
Watchdog error: Cannot read LSP request: A Lean 3 request was received. Please ensure that your editor has a Lean 4 compatible extension installed. For VSCode, this is
```

As you can see I installed Lean4 on the right of the screenshot using Elan.

Please make this useful tool work.   Thanks.

**Comment by eric-wieser** [comment]
This repository is only for Lean 3.

**Comment by enjoysmath** [comment]
Where's the one for Lean4?

**Comment by eric-wieser** [comment]
There isn't one, and probably won't ever be; Lean 4 speaks the standard language server protocol rather than inventing its own LSP. Presumably there are python clients somewhere for that.
